name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Give the job permission to write to the repository contents
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch themes (if used as submodules)
          fetch-depth: 0    # Fetch all history

      - name: Setup Hugo
        # Installs the latest version of Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' 

      - name: Build Hugo Site
        # Runs the main Hugo build command
        run: hugo --minify

      - name: Deploy to GitHub Pages
        # Deploys the content of the 'public' folder to the 'gh-pages' branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages